### ISSUE TITLE
load plugin gitbook-plugin-sitemap error

### ISSUE THREAD

**Issue by zhaoda** [GitbookIO/plugin-sitemap#1]
I have run `gitbook install`, but some error there.

gitbook-cli version 1.0.0

``` bash
info: load plugin gitbook-plugin-sitemap ....ERROR

Error: Error loading plugins: gitbook-plugin-sitemap. Run 'gitbook install' to install plugins from NPM.
```

**Comment by SamyPesse** [comment]
What is the output of `gitbook versions:print` ?

**Comment by SamyPesse** [comment]
It works for me with GitBook 2.5.2.

**Comment by zhaoda** [comment]
GitBook version is 2.5.2
node.js version 4.2.1

**Comment by zhaoda** [comment]
Must be installed on the plugin directory.

``` bash
$ cd ./content/node_modules/gitbook-plugin-sitemap
$ npm install
```

Like this https://github.com/zhaoda/webpack-handbook
