### ISSUE TITLE
wrong links in sitemap

### ISSUE THREAD

**Issue by petrosliu** [GitbookIO/plugin-sitemap#6]
Hi, I add the sitemap plugin in my gitbook with "hostname": "http://codenote.liuyid.in/". However, in the sitemap http://codenote.liuyid.in/sitemap.xml, all links are wrong with additional "null"s, like http://codenote.liuyid.in/nullREADME.html .

**Comment by skcc75** [comment]
+1

@SamyPesse

**Comment by skcc75** [comment]
@petrosliu seems to work with GitBook v3

**Comment by petrosliu** [comment]
@kyrylkov you are right. Thanks!

**Comment by Simran-B** [comment]
How to fix it for GitBook 2.x? I can't upgrade to 3.0 because it breaks too many things and has several bugs.
